import { Card } from './card.model'

export type DeckCards = [
  Card<'ACE', 'CLUBS'>,
  Card<'TWO', 'CLUBS'>,
  Card<'THREE', 'CLUBS'>,
  Card<'FOUR', 'CLUBS'>,
  Card<'FIVE', 'CLUBS'>,
  Card<'SIX', 'CLUBS'>,
  Card<'SEVEN', 'CLUBS'>,
  Card<'EIGHT', 'CLUBS'>,
  Card<'NINE', 'CLUBS'>,
  Card<'TEN', 'CLUBS'>,
  Card<'JACK', 'CLUBS'>,
  Card<'QUEEN', 'CLUBS'>,
  Card<'KING', 'CLUBS'>,
  Card<'ACE', 'DIAMONDS'>,
  Card<'TWO', 'DIAMONDS'>,
  Card<'THREE', 'DIAMONDS'>,
  Card<'FOUR', 'DIAMONDS'>,
  Card<'FIVE', 'DIAMONDS'>,
  Card<'SIX', 'DIAMONDS'>,
  Card<'SEVEN', 'DIAMONDS'>,
  Card<'EIGHT', 'DIAMONDS'>,
  Card<'NINE', 'DIAMONDS'>,
  Card<'TEN', 'DIAMONDS'>,
  Card<'JACK', 'DIAMONDS'>,
  Card<'QUEEN', 'DIAMONDS'>,
  Card<'KING', 'DIAMONDS'>,
  Card<'ACE', 'HEARTS'>,
  Card<'TWO', 'HEARTS'>,
  Card<'THREE', 'HEARTS'>,
  Card<'FOUR', 'HEARTS'>,
  Card<'FIVE', 'HEARTS'>,
  Card<'SIX', 'HEARTS'>,
  Card<'SEVEN', 'HEARTS'>,
  Card<'EIGHT', 'HEARTS'>,
  Card<'NINE', 'HEARTS'>,
  Card<'TEN', 'HEARTS'>,
  Card<'JACK', 'HEARTS'>,
  Card<'QUEEN', 'HEARTS'>,
  Card<'KING', 'HEARTS'>,
  Card<'ACE', 'SPADES'>,
  Card<'TWO', 'SPADES'>,
  Card<'THREE', 'SPADES'>,
  Card<'FOUR', 'SPADES'>,
  Card<'FIVE', 'SPADES'>,
  Card<'SIX', 'SPADES'>,
  Card<'SEVEN', 'SPADES'>,
  Card<'EIGHT', 'SPADES'>,
  Card<'NINE', 'SPADES'>,
  Card<'TEN', 'SPADES'>,
  Card<'JACK', 'SPADES'>,
  Card<'QUEEN', 'SPADES'>,
  Card<'KING', 'SPADES'>,
]

export class Deck {
  constructor(public readonly cards: DeckCards) {}

  static createNew() {
    return new Deck([
      { value: 'ACE', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'TWO', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'THREE', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'FOUR', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'FIVE', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'SIX', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'SEVEN', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'EIGHT', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'NINE', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'TEN', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'JACK', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'QUEEN', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'KING', suit: 'CLUBS', status: 'UNASSIGNED' },
      { value: 'ACE', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'TWO', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'THREE', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'FOUR', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'FIVE', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'SIX', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'SEVEN', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'EIGHT', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'NINE', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'TEN', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'JACK', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'QUEEN', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'KING', suit: 'DIAMONDS', status: 'UNASSIGNED' },
      { value: 'ACE', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'TWO', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'THREE', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'FOUR', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'FIVE', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'SIX', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'SEVEN', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'EIGHT', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'NINE', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'TEN', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'JACK', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'QUEEN', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'KING', suit: 'HEARTS', status: 'UNASSIGNED' },
      { value: 'ACE', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'TWO', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'THREE', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'FOUR', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'FIVE', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'SIX', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'SEVEN', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'EIGHT', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'NINE', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'TEN', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'JACK', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'QUEEN', suit: 'SPADES', status: 'UNASSIGNED' },
      { value: 'KING', suit: 'SPADES', status: 'UNASSIGNED' },
    ])
  }
}
